// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using TripTracker.Entities.Entities;

namespace TripTracker.DataAccess.Context;

public partial class db33063Context : DbContext
{
    public db33063Context(DbContextOptions<db33063Context> options)
        : base(options)
    {
    }

    public db33063Context()
    {
    }

    public virtual DbSet<tbAreas> tbAreas { get; set; }

    public virtual DbSet<tbCargos> tbCargos { get; set; }

    public virtual DbSet<tbColaboradores> tbColaboradores { get; set; }

    public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }

    public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }

    public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }

    public virtual DbSet<tbPantallas> tbPantallas { get; set; }

    public virtual DbSet<tbPantallasPorRol> tbPantallasPorRol { get; set; }

    public virtual DbSet<tbRoles> tbRoles { get; set; }

    public virtual DbSet<tbSolicitudesListas> tbSolicitudesListas { get; set; }

    public virtual DbSet<tbSucursales> tbSucursales { get; set; }

    public virtual DbSet<tbSucursalesPorColaborador> tbSucursalesPorColaborador { get; set; }

    public virtual DbSet<tbTransportistas> tbTransportistas { get; set; }

    public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }

    public virtual DbSet<tbViajes> tbViajes { get; set; }

    public virtual DbSet<tbViajesDetalle> tbViajesDetalle { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tbAreas>(entity =>
        {
            entity.HasKey(e => e.Area_Id).HasName("PK_Gral_tbAreas_Area_Id");

            entity.ToTable("tbAreas", "Gral");

            entity.Property(e => e.Area_Descripcion)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Area_Estado).HasDefaultValue(true);
            entity.Property(e => e.Area_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Area_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbAreasUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbAreas_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbAreasUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Gral_tbArea_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbCargos>(entity =>
        {
            entity.HasKey(e => e.Carg_Id).HasName("PK_Gral_tbCargos_Carg_Id");

            entity.ToTable("tbCargos", "Gral");

            entity.Property(e => e.Carg_Descripcion)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Carg_Estado).HasDefaultValue(true);
            entity.Property(e => e.Carg_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Carg_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbCargosUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbCargos_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbCargosUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Gral_tbCargos_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbColaboradores>(entity =>
        {
            entity.HasKey(e => e.Colb_Id).HasName("PK_Gral_tbColaboradores_Colb_Id");

            entity.ToTable("tbColaboradores", "Gral");

            entity.HasIndex(e => e.Colb_DNI, "UQ__tbColabo__9480D753CD70EFB2").IsUnique();

            entity.Property(e => e.Colb_Apellidos)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Colb_DNI)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Colb_Direccion)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Colb_Estado).HasDefaultValue(true);
            entity.Property(e => e.Colb_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Colb_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Colb_Nombres)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Colb_Sexo)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.Colb_Telefono)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Muni_Codigo)
                .HasMaxLength(4)
                .IsUnicode(false);

            entity.HasOne(d => d.Area).WithMany(p => p.tbColaboradores)
                .HasForeignKey(d => d.Area_Id)
                .HasConstraintName("FK_Gral_tbColaboradores_Gral_tbAreas_Area_Id");

            entity.HasOne(d => d.Carg).WithMany(p => p.tbColaboradores)
                .HasForeignKey(d => d.Carg_Id)
                .HasConstraintName("FK_Gral_tbColaboradores_Gral_tbCargos_Carg_Id");

            entity.HasOne(d => d.EsCi).WithMany(p => p.tbColaboradores)
                .HasForeignKey(d => d.EsCi_Id)
                .HasConstraintName("FK_Gral_tbColaboradores_Gral_tbEstadosCiviles_EsCi_Id");

            entity.HasOne(d => d.Muni_CodigoNavigation).WithMany(p => p.tbColaboradores)
                .HasForeignKey(d => d.Muni_Codigo)
                .HasConstraintName("FK_Gral_tbColaboradores_Gral_tbMunicipios_Muni_Codigo");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbColaboradoresUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbColaboradores_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbColaboradoresUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Gral_tbColaboradores_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbDepartamentos>(entity =>
        {
            entity.HasKey(e => e.Depa_Codigo).HasName("PK_Gral_tbDepartamentos_Depa_Codigo");

            entity.ToTable("tbDepartamentos", "Gral");

            entity.Property(e => e.Depa_Codigo)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.Depa_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Depa_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Depa_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbDepartamentosUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .HasConstraintName("FK_Gral_tbDepartamentos_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbDepartamentosUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Gral_tbDepartamentos_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbEstadosCiviles>(entity =>
        {
            entity.HasKey(e => e.EsCi_Id).HasName("PK_Gral_tbEstadosCiviles_EsCi_Id");

            entity.ToTable("tbEstadosCiviles", "Gral");

            entity.Property(e => e.EsCi_Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EsCi_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.EsCi_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbEstadosCivilesUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbEstadosCiviles_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbEstadosCivilesUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Gral_tbEstadosCiviles_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbMunicipios>(entity =>
        {
            entity.HasKey(e => e.Muni_Codigo).HasName("PK_Gral_tbMunicipios_Muni_Codigo");

            entity.ToTable("tbMunicipios", "Gral");

            entity.Property(e => e.Muni_Codigo)
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.Depa_Codigo)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.Muni_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Muni_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Muni_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Depa_CodigoNavigation).WithMany(p => p.tbMunicipios)
                .HasForeignKey(d => d.Depa_Codigo)
                .HasConstraintName("FK_Gral_tbMunicipios_Gral_tbDepartamentos_Depa_Codigo");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbMunicipiosUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .HasConstraintName("FK_Gral_tbMunicipios_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbMunicipiosUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Gral_tbMunicipios_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbPantallas>(entity =>
        {
            entity.HasKey(e => e.Pant_Id).HasName("PK_Acce_Pantallas_Pant_Id");

            entity.ToTable("tbPantallas", "Acce");

            entity.Property(e => e.Pant_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Pant_Ruta)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Pant_Schema)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<tbPantallasPorRol>(entity =>
        {
            entity.HasKey(e => e.PaRo_Id).HasName("PK_Acce_tbPantallasPorRol");

            entity.ToTable("tbPantallasPorRol", "Acce");

            entity.Property(e => e.PaRo_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.PaRo_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Pant).WithMany(p => p.tbPantallasPorRol)
                .HasForeignKey(d => d.Pant_Id)
                .HasConstraintName("FK_Acce_tbPantallasPorRol_Pant_Id");

            entity.HasOne(d => d.Role).WithMany(p => p.tbPantallasPorRol)
                .HasForeignKey(d => d.Role_Id)
                .HasConstraintName("FK_Acce_tbPantallasPorRol_Role_Id");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbPantallasPorRol)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Acce_tbPantallasPorRol_Usua_Modificacion");
        });

        modelBuilder.Entity<tbRoles>(entity =>
        {
            entity.HasKey(e => e.Role_Id).HasName("PK_Acce_Roles");

            entity.ToTable("tbRoles", "Acce");

            entity.Property(e => e.Role_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Role_Estado).HasDefaultValue(true);
            entity.Property(e => e.Role_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Role_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbRolesUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_Roles_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbRolesUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Acce_Roles_Usua_Modificacion");
        });

        modelBuilder.Entity<tbSolicitudesListas>(entity =>
        {
            entity.HasKey(e => e.SoLi_Id).HasName("PK_Viaj_tbSolicitudesListas_SoLi_Id");

            entity.ToTable("tbSolicitudesListas", "Viaj");

            entity.Property(e => e.SoLi_Fecha).HasColumnType("datetime");
            entity.Property(e => e.SoLi_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.SoLi_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.SuCo).WithMany(p => p.tbSolicitudesListas)
                .HasForeignKey(d => d.SuCo_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Viaj_tbSolicitudesListas_Acce_tbSucursalesPorColaborador_SuCo_Id");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbSolicitudesListasUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Viaj_tbSolicitudesListas_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbSolicitudesListasUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Viaj_tbSolicitudesListas_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbSucursales>(entity =>
        {
            entity.HasKey(e => e.Sucu_Id).HasName("PK_Gral_tbSucursales_Sucu_Id");

            entity.ToTable("tbSucursales", "Gral");

            entity.Property(e => e.Muni_Codigo)
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.Sucu_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Sucu_Estado).HasDefaultValue(true);
            entity.Property(e => e.Sucu_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Sucu_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Muni_CodigoNavigation).WithMany(p => p.tbSucursales)
                .HasForeignKey(d => d.Muni_Codigo)
                .HasConstraintName("FK_Gral_tbSucursales_Gral_tbMunicipios_Muni_Codigo");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbSucursalesUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbSucursales_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbSucursalesUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Gral_tbSucursales_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbSucursalesPorColaborador>(entity =>
        {
            entity.HasKey(e => e.SuCo_Id).HasName("PK_Viaj_tbSucursalesPorColaborador_SuCo_Id");

            entity.ToTable("tbSucursalesPorColaborador", "Viaj");

            entity.HasIndex(e => new { e.Sucu_Id, e.Colb_Id }, "UQ_Viaj_tbSucursalesPorColaborador_Sucu_Colb").IsUnique();

            entity.Property(e => e.SuCo_DistanciaCasa).HasColumnType("numeric(4, 2)");
            entity.Property(e => e.SuCo_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.SuCo_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Colb).WithMany(p => p.tbSucursalesPorColaborador)
                .HasForeignKey(d => d.Colb_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Viaj_tbSucursalesPorColaborador_Gral_tbColaboradores_Colb_Id");

            entity.HasOne(d => d.Sucu).WithMany(p => p.tbSucursalesPorColaborador)
                .HasForeignKey(d => d.Sucu_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Viaj_tbSucursalesPorColaborador_Gral_tbSucursales_Sucu_Id");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbSucursalesPorColaboradorUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Viaj_tbSucursalesPorColaborador_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbSucursalesPorColaboradorUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Viaj_tbSucursalesPorColaborador_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbTransportistas>(entity =>
        {
            entity.HasKey(e => e.Trpo_Id).HasName("PK_Viaj_tbTransportistas_Trpo_Id");

            entity.ToTable("tbTransportistas", "Viaj");

            entity.Property(e => e.Trpo_Apellidos)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Trpo_DNI)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Trpo_Estado).HasDefaultValue(true);
            entity.Property(e => e.Trpo_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Trpo_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Trpo_Nombres)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Trpo_Placa)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Trpo_Sexo)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.Trpo_TarifaKM).HasColumnType("numeric(8, 2)");
            entity.Property(e => e.Trpo_Vehiculo)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbTransportistasUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Viaj_tbTransportistas_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbTransportistasUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Viaj_tbTransportistas_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbUsuarios>(entity =>
        {
            entity.HasKey(e => e.Usua_Id).HasName("PK_Acce_tbUsuarios");

            entity.ToTable("tbUsuarios", "Acce");

            entity.Property(e => e.Usua_Admin).HasDefaultValue(false);
            entity.Property(e => e.Usua_Contrasena)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Usua_Estado).HasDefaultValue(true);
            entity.Property(e => e.Usua_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Usua_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Usua_Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Colb).WithMany(p => p.tbUsuarios)
                .HasForeignKey(d => d.Colb_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbUsuarios_Colb_Id");

            entity.HasOne(d => d.Role).WithMany(p => p.tbUsuarios)
                .HasForeignKey(d => d.Role_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbUsuarios_Role_Id");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.InverseUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbUsuarios_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.InverseUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Acce_tbUsuarios_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbViajes>(entity =>
        {
            entity.HasKey(e => e.Viaj_Id).HasName("PK_Viaj_tbViajes_Viaj_Id");

            entity.ToTable("tbViajes", "Viaj");

            entity.Property(e => e.Viaj_Estado).HasDefaultValue(true);
            entity.Property(e => e.Viaj_Fecha).HasColumnType("datetime");
            entity.Property(e => e.Viaj_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Viaj_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Viaj_TarifaKM).HasColumnType("numeric(8, 2)");
            entity.Property(e => e.Viaj_TarifaTotal).HasColumnType("numeric(8, 2)");

            entity.HasOne(d => d.Sucu).WithMany(p => p.tbViajes)
                .HasForeignKey(d => d.Sucu_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Viaj_tbViajes_Gral_tbSucursales_Sucu_Id");

            entity.HasOne(d => d.Trpo).WithMany(p => p.tbViajes)
                .HasForeignKey(d => d.Trpo_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Viaj_tbViajes_Viaj_tbTransportistas_Trpo_Id");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbViajesUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Viaj_tbViajes_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbViajesUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Viaj_tbViajes_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbViajesDetalle>(entity =>
        {
            entity.HasKey(e => e.ViDt_Id).HasName("PK_Viaj_tbViajesDetalle_ViDt_Id");

            entity.ToTable("tbViajesDetalle", "Viaj");

            entity.Property(e => e.ViDt_DistanciaCasa).HasColumnType("numeric(4, 2)");
            entity.Property(e => e.ViDt_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.ViDt_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.SuCo).WithMany(p => p.tbViajesDetalle)
                .HasForeignKey(d => d.SuCo_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Viaj_tbViajesDetalle_Viaj_tbSucursalesPorColaborador_SuCo_Id");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbViajesDetalleUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Viaj_tbViajesDetalle_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbViajesDetalleUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Viaj_tbViajesDetalle_Acce_tbUsuarios_Usua_Modificacion");

            entity.HasOne(d => d.Viaj).WithMany(p => p.tbViajesDetalle)
                .HasForeignKey(d => d.Viaj_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Viaj_tbViajesDetalle_Viaj_tbViajes_Viaj_Id");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}