// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TripTracker.Entities.Entities;

public partial class tbColaboradores
{
    public int Colb_Id { get; set; }

    public string Colb_DNI { get; set; }

    public string Colb_Nombres { get; set; }

    public string Colb_Apellidos { get; set; }

    public string Colb_Telefono { get; set; }

    public string Colb_Sexo { get; set; }

    public string Colb_Direccion { get; set; }

    public int? EsCi_Id { get; set; }

    public string Muni_Codigo { get; set; }

    public int? Area_Id { get; set; }

    public int? Carg_Id { get; set; }

    public bool? Colb_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Colb_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Colb_FechaModificacion { get; set; }

    public virtual tbAreas Area { get; set; }

    public virtual tbCargos Carg { get; set; }

    public virtual tbEstadosCiviles EsCi { get; set; }

    public virtual tbMunicipios Muni_CodigoNavigation { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbSucursalesPorColaborador> tbSucursalesPorColaborador { get; set; } = new List<tbSucursalesPorColaborador>();

    public virtual ICollection<tbUsuarios> tbUsuarios { get; set; } = new List<tbUsuarios>();
}