// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TripTracker.Entities.Entities;

public partial class tbEstadosCiviles
{
    public int EsCi_Id { get; set; }

    public string EsCi_Descripcion { get; set; }

    public DateTime EsCi_FechaCreacion { get; set; }

    public DateTime? EsCi_FechaModificacion { get; set; }

    public int Usua_Creacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbColaboradores> tbColaboradores { get; set; } = new List<tbColaboradores>();
}