// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TripTracker.Entities.Entities;

public partial class tbPantallas
{
    public int Pant_Id { get; set; }

    public string Pant_Descripcion { get; set; }

    public string Pant_Ruta { get; set; }

    public string Pant_Schema { get; set; }

    public virtual ICollection<tbPantallasPorRol> tbPantallasPorRol { get; set; } = new List<tbPantallasPorRol>();
}