// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TripTracker.Entities.Entities;

public partial class tbSolicitudesListas
{
    public int SoLi_Id { get; set; }

    public DateTime SoLi_Fecha { get; set; }

    public int SuCo_Id { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime SoLi_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? SoLi_FechaModificacion { get; set; }

    public virtual tbSucursalesPorColaborador SuCo { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}