// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TripTracker.Entities.Entities;

public partial class tbSucursales
{
    public int Sucu_Id { get; set; }

    public string Sucu_Descripcion { get; set; }

    public string Muni_Codigo { get; set; }

    public bool? Sucu_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Sucu_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Sucu_FechaModificacion { get; set; }

    public virtual tbMunicipios Muni_CodigoNavigation { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbSucursalesPorColaborador> tbSucursalesPorColaborador { get; set; } = new List<tbSucursalesPorColaborador>();

    public virtual ICollection<tbViajes> tbViajes { get; set; } = new List<tbViajes>();
}