// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TripTracker.Entities.Entities;

public partial class tbSucursalesPorColaborador
{
    public int SuCo_Id { get; set; }

    public decimal? SuCo_DistanciaCasa { get; set; }

    public int Sucu_Id { get; set; }

    public int Colb_Id { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime SuCo_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? SuCo_FechaModificacion { get; set; }

    public virtual tbColaboradores Colb { get; set; }

    public virtual tbSucursales Sucu { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbSolicitudesListas> tbSolicitudesListas { get; set; } = new List<tbSolicitudesListas>();

    public virtual ICollection<tbViajesDetalle> tbViajesDetalle { get; set; } = new List<tbViajesDetalle>();
}