// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TripTracker.Entities.Entities;

public partial class tbTransportistas
{
    public int Trpo_Id { get; set; }

    public string Trpo_DNI { get; set; }

    public string Trpo_Nombres { get; set; }

    public string Trpo_Apellidos { get; set; }

    public decimal Trpo_TarifaKM { get; set; }

    public string Trpo_Sexo { get; set; }

    public string Trpo_Placa { get; set; }

    public string Trpo_Vehiculo { get; set; }

    public bool? Trpo_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Trpo_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Trpo_FechaModificacion { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbViajes> tbViajes { get; set; } = new List<tbViajes>();
}