// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TripTracker.Entities.Entities;

public partial class tbUsuarios
{
    public int Usua_Id { get; set; }

    public string Usua_Nombre { get; set; }

    public string Usua_Contrasena { get; set; }

    public bool? Usua_Admin { get; set; }

    public int Colb_Id { get; set; }

    public int Role_Id { get; set; }

    public bool? Usua_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime Usua_FechaCreacion { get; set; }

    public DateTime? Usua_FechaModificacion { get; set; }

    public virtual tbColaboradores Colb { get; set; }

    public virtual ICollection<tbUsuarios> InverseUsua_CreacionNavigation { get; set; } = new List<tbUsuarios>();

    public virtual ICollection<tbUsuarios> InverseUsua_ModificacionNavigation { get; set; } = new List<tbUsuarios>();

    public virtual tbRoles Role { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbAreas> tbAreasUsua_CreacionNavigation { get; set; } = new List<tbAreas>();

    public virtual ICollection<tbAreas> tbAreasUsua_ModificacionNavigation { get; set; } = new List<tbAreas>();

    public virtual ICollection<tbCargos> tbCargosUsua_CreacionNavigation { get; set; } = new List<tbCargos>();

    public virtual ICollection<tbCargos> tbCargosUsua_ModificacionNavigation { get; set; } = new List<tbCargos>();

    public virtual ICollection<tbColaboradores> tbColaboradoresUsua_CreacionNavigation { get; set; } = new List<tbColaboradores>();

    public virtual ICollection<tbColaboradores> tbColaboradoresUsua_ModificacionNavigation { get; set; } = new List<tbColaboradores>();

    public virtual ICollection<tbDepartamentos> tbDepartamentosUsua_CreacionNavigation { get; set; } = new List<tbDepartamentos>();

    public virtual ICollection<tbDepartamentos> tbDepartamentosUsua_ModificacionNavigation { get; set; } = new List<tbDepartamentos>();

    public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesUsua_CreacionNavigation { get; set; } = new List<tbEstadosCiviles>();

    public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesUsua_ModificacionNavigation { get; set; } = new List<tbEstadosCiviles>();

    public virtual ICollection<tbMunicipios> tbMunicipiosUsua_CreacionNavigation { get; set; } = new List<tbMunicipios>();

    public virtual ICollection<tbMunicipios> tbMunicipiosUsua_ModificacionNavigation { get; set; } = new List<tbMunicipios>();

    public virtual ICollection<tbPantallasPorRol> tbPantallasPorRol { get; set; } = new List<tbPantallasPorRol>();

    public virtual ICollection<tbRoles> tbRolesUsua_CreacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbRoles> tbRolesUsua_ModificacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbSolicitudesListas> tbSolicitudesListasUsua_CreacionNavigation { get; set; } = new List<tbSolicitudesListas>();

    public virtual ICollection<tbSolicitudesListas> tbSolicitudesListasUsua_ModificacionNavigation { get; set; } = new List<tbSolicitudesListas>();

    public virtual ICollection<tbSucursalesPorColaborador> tbSucursalesPorColaboradorUsua_CreacionNavigation { get; set; } = new List<tbSucursalesPorColaborador>();

    public virtual ICollection<tbSucursalesPorColaborador> tbSucursalesPorColaboradorUsua_ModificacionNavigation { get; set; } = new List<tbSucursalesPorColaborador>();

    public virtual ICollection<tbSucursales> tbSucursalesUsua_CreacionNavigation { get; set; } = new List<tbSucursales>();

    public virtual ICollection<tbSucursales> tbSucursalesUsua_ModificacionNavigation { get; set; } = new List<tbSucursales>();

    public virtual ICollection<tbTransportistas> tbTransportistasUsua_CreacionNavigation { get; set; } = new List<tbTransportistas>();

    public virtual ICollection<tbTransportistas> tbTransportistasUsua_ModificacionNavigation { get; set; } = new List<tbTransportistas>();

    public virtual ICollection<tbViajesDetalle> tbViajesDetalleUsua_CreacionNavigation { get; set; } = new List<tbViajesDetalle>();

    public virtual ICollection<tbViajesDetalle> tbViajesDetalleUsua_ModificacionNavigation { get; set; } = new List<tbViajesDetalle>();

    public virtual ICollection<tbViajes> tbViajesUsua_CreacionNavigation { get; set; } = new List<tbViajes>();

    public virtual ICollection<tbViajes> tbViajesUsua_ModificacionNavigation { get; set; } = new List<tbViajes>();
}