// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TripTracker.Entities.Entities;

public partial class tbViajes
{
    public int Viaj_Id { get; set; }

    public DateTime Viaj_Fecha { get; set; }

    public decimal? Viaj_TarifaTotal { get; set; }

    public decimal Viaj_TarifaKM { get; set; }

    public int Trpo_Id { get; set; }

    public int Sucu_Id { get; set; }

    public bool? Viaj_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Viaj_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Viaj_FechaModificacion { get; set; }

    public virtual tbSucursales Sucu { get; set; }

    public virtual tbTransportistas Trpo { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbViajesDetalle> tbViajesDetalle { get; set; } = new List<tbViajesDetalle>();
}