// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TripTracker.Entities.Entities;

public partial class tbViajesDetalle
{
    public int ViDt_Id { get; set; }

    public decimal ViDt_DistanciaCasa { get; set; }

    public int Viaj_Id { get; set; }

    public int SuCo_Id { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime ViDt_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? ViDt_FechaModificacion { get; set; }

    public virtual tbSucursalesPorColaborador SuCo { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual tbViajes Viaj { get; set; }
}